SOFTWARE_NAME = "Python"
INSERT_QUERY = "INSERT INTO Softwares(SNO,SOFTWARE,LOCATION) VALUES (1,%s,%s)"
LOCAL_FILE_PATH = "downloaded_python.exe"
SOFTWARE_URL = "https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe"
FILE_NAME = "python-3.11.4-amd64.exe"